### PR TITLE
Math magician app: Refactor with hooks

### PR DESCRIPTION
**Pull request by BertrandConxy**
# Math magician app: Refactor with hooks

In this branch, I have done the following:
- Refactored the Calculator.js from class component to functional component.
- added new stylings
- solved some bugs on the `=` button

### CODE REVIEW

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
Hi @BertrandConxy 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet, please work on it and ask for another review.


 ## Required Changes ♻️
 
 - Your calculator is missing the `.` button, kindly implement it and its functionality.
 - How about refactoring with the hooks in the `app.js`.
 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by BertrandConxy** [comment]
Thank you @Emmyn5600  for your review. In the recent Commit I made, I have implemented all the suggested improvement.
I have refactored the App.js and also added the period `.` button.

**Review by Meltrust — APPROVED** [review]
Hi @BertrandConxy,


## Wow, you did it 🎉
Brilliant
## Thank you for converting your `App.js` to function and adding the `.` to your calculator, as  requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BertrandConxy** [comment]
Thank you @Meltrust  for your review.

**Pull request merged**
